#!/usr/bin/env ruby

# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

# Other plugins
# * Git
#     git://github.com/tpope/vim-fugitive.git
#     git://github.com/tpope/vim-git.git
# * File explorer / navigation
#     git://github.com/scrooloose/nerdtree.git
#     git://github.com/vim-scripts/project.tar.gz
# * Comments
#     git://github.com/tsaleh/vim-tcomment.git
# * Autocomplete
#     git://github.com/ervandew/supertab.git
# * Python
#     git://github.com/fs111/pydoc.vim.git
# * Ruby
#     git://github.com/tsaleh/vim-shoulda.git
#     git://github.com/tpope/vim-rails.git
#     git://github.com/tpope/vim-cucumber.git
#     git://github.com/astashov/vim-ruby-debugger.git
# * Markup
#     git://github.com/tpope/vim-haml.git

vim_org_scripts = [
  ["anotherdark", "4449", "colors"], # http://www.vim.org/scripts/script.php?script_id=1308
]

# xmledit for other filetypes
xmledit_filetypes = ["ant", "html", "sgml", "xhtml"]

require 'fileutils'
require 'open-uri'

puts "Updating bundles"

puts "  Updating submodules"
`git submodule init`
`git submodule update --recursive`

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.cd(bundles_dir)

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Removing #{name}"
  FileUtils.rm_rf name
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

puts "  Xmledit for other filetypes"
xmledit_filetypes.each do |filetype|
  target = File.expand_path("./xmledit/ftplugin/#{filetype}.vim")
  if not File.exist? target
    FileUtils.ln_s(File.expand_path("./xmledit/ftplugin/xml.vim"), target)
  end
end

# Build command-t
FileUtils.cd("command-t")
puts "  Building command-t"
`rake make`

